name: First Python CI
on:
  push:
    branches: [ "main" ]

jobs:
  basic-tests:
    runs-on: ubuntu-latest
    steps:
    # Check out the repository
    - uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Run pytest
    - name: Run pytest
      run: |
        pytest
